#!/bin/bash

if [ -z "$2" ]
then
	fps="25"
else
	fps=$2
fi

if [ $1 -eq 1 ]
then
	alacritty -e ffmpeg -video_size 3840x2160 -framerate $fps -f x11grab -i :0.0+0,0 ~/Vidéos/screen.mp4
fi
if [ $1 -eq 2 ]
then
	alacritty -e ffmpeg -video_size 2560x1440 -framerate $fps -f x11grab -i :0.0+3840,0 ~/Vidéos/screen.mp4
fi
